version: "3.8"

services:
  app:
    image: szakdolgozat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/thesis
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Festool51@
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: Festool51@
      MYSQL_DATABASE: Thesis
      MYSQL_USER: admin
      MYSQL_PASSWORD: Festool51@
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h db -P 3306 -u root -pFestool51@" ]
      interval: 10s
      timeout: 5s
      retries: 3
  angular:
    image: szakdolgozat-fronted
    build:
      context: D:\Szakdolgozat_frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80
