version: "3.8"

services:
  app:
    image: szakdolgozat
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/thesis
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Festool51@
    depends_on:
      - db
  db:
    image: mysql
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: Festool51@
      MYSQL_DATABASE: Thesis
      MYSQL_USER: admin
      MYSQL_PASSWORD: Festool51@


